---
# Dummy values — overridden by vault.yml

ansible_host: "192.168.124.105"
host_octet: 105
mailname: "spark5.example.com"
default_route_iface: "br0.125"
clevis_luks_passphrase: "changeme"
qsfp_ip: "10.10.10.5"
k3s_node_ip: "192.168.124.105"

wantspodman: true