---
# Dummy values — overridden by vault.yml

ansible_host: "192.168.123.3"
ansible_password: "changeme"
serial_number: "CHANGEME"
# ansible_private_key_file: "~/.ssh/id_ed25519"
# ansible_network_cli_ssh_type: libssh
ansible_ssh_user: "mikrotikadmin"

mikrotik_bridge_name: bridge

mikrotik_bridge_ports:
  - interface: ether1
    comment: "Uplink (Mikrotik CRS310-8G-2S)"
  - interface: qsfp56-1-1
    comment: "spark1 QSFP56 1x100G"
  - interface: qsfp56-2-1
    comment: "spark2 QSFP56 1x100G"
  - interface: qsfp56-dd-1-1
    comment: "spark3 QSFP-DD 1x400G"
  - interface: qsfp56-dd-2-1
    comment: "spark4 QSFP-DD 1x400G"

# No VLANs — pure L2 bridge (real values in vault.yml)
mikrotik_bridge_vlans: []
mikrotik_mgmt_interfaces: []

mikrotik_default_gateway: "192.168.123.2"
mikrotik_dns_servers:
  - "192.168.123.1"

# RoCE/RDMA lossless Ethernet on QSFP ports
mikrotik_qsfp_roce_ports:
  - name: qsfp56-1-1
    egress_rate: "200.0Gbps"
  - name: qsfp56-2-1
    egress_rate: "200.0Gbps"
  - name: qsfp56-dd-1-1
    egress_rate: "200.0Gbps"  # "400.0Gbps", but currently directly connected to spark3 -> no breakout cable
  - name: qsfp56-dd-2-1
    egress_rate: "200.0Gbps"  # "400.0Gbps", but currently directly connected to spark4 -> no breakout cable
